<?php

namespace FernleafSystems\ApiWrappers\Pushover;

use FernleafSystems\ApiWrappers\Base\BaseApi;

/**
 * Class Api
 * @package FernleafSystems\ApiWrappers\FreeAgent
 */
class Api extends BaseApi {

	const REQUEST_METHOD = 'post';

	/**
	 * @return string
	 */
	protected function getBaseUrl() {
		/** @var Connection $oConn */
		$oConn = $this->getConnection();
		return sprintf( '%s/%s', $oConn->getBaseUrl(), $oConn->getApiVersion() ).'/';
	}

	/**
	 * @return string
	 */
	public function getUserKey() {
		/** @var Connection $oConn */
		$oConn = $this->getConnection();
		$sKey = $this->getStringParam( 'user_key' );
		return empty( $sKey ) ? $oConn->getUserKey() : $sKey;
	}

	/**
	 * @return bool
	 */
	public function isLastRequestSuccess() {
		$bSuccess = parent::isLastRequestSuccess(); // TODO: Change the autogenerated stub
		if ( $bSuccess ) {
			$aResp = $this->getDecodedResponseBody();
			$bSuccess = is_array( $aResp ) && isset( $aResp[ 'status' ] ) && $aResp[ 'status' ] == 1;
		}
		return $bSuccess;
	}

	/**
	 * @return array
	 */
	protected function prepFinalRequestData() {
		$this->setRequestDataItem( 'token', $this->getConnection()->getApiKey() )
			 ->setRequestDataItem( 'user', $this->getUserKey() );
		return parent::prepFinalRequestData();
	}

	/**
	 * @param string $sValue
	 * @return $this
	 */
	public function setDevice( $sValue ) {
		return $this->setRequestDataItem( 'device', $sValue );
	}

	/**
	 * Use this to override the User Key set in the Connection
	 * @param string $sKey
	 * @return $this
	 */
	public function setUserKey( $sKey ) {
		return $this->setParam( 'user_key', $sKey );
	}
}